### ISSUE TITLE
Docs links throw 404 in certain scenarios

### ISSUE THREAD

**Issue by ivpavici** [starknet-community-libs/starknet-docs#44]
**Describe the bug**
Docs links throw 404 in certain scenarios, explained in steps to reproduce

**To Reproduce**

1. For example open this page:
https://docs.starknet.io/docs/Blocks/transactions#chain-id
2. If you refresh the page, the link changes to:
https://docs.starknet.io/docs/Blocks/transactions/#chain-id
(notice the slash before #chain-id)
3. after that other links don't work also, because link for pedersen hash becomes:
https://docs.starknet.io/docs/Blocks/Hashing/hash-functions#pedersen-hash
instead of:
https://docs.starknet.io/docs/Hashing/hash-functions#pedersen-hash

**Expected behavior**
Links should work in all scenarios

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge  102.0.1245.33 and Firefox 101

**Comment by stoobie** [comment]
@ivpavici Sorry I didn't address this for so long. I believe that this comment is now addressed. I'd appreciate it if you could check it out when you get a chance.

**Comment by ivpavici** [comment]
Yeah it's ok! Thanks!
